services:
  - type: web
    name: pixelscribe-bot
    env: node
    plan: free
    buildCommand: npm install && npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: BOT_EMAIL
        sync: false
      - key: BOT_PASSWORD
        sync: false
      - key: API_BASE_URL
        value: https://pixelscribe3.vercel.app
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/node_modules/playwright/.local-browsers
